#6feature/todotop
if-mentor/next_todo10 pull request #13
Opened 2023-05-13 05:31 UTC by riennnn

- screen shot 
<img width="1440" alt="スクリーンショット 2023-05-13 14 27 05" src="https://github.com/if-mentor/next_todo10/assets/107998390/cbb71bd3-ba62-434a-9f6b-e4dd964a3aba">

2023-05-13 13:31 UTC, shtk0119 requested changes
package-lock.jsonファイルは消去していただくようお願いします。

2023-05-15 10:25 UTC, riennnn commented on top.component/resetButton.jsx
> +    </Box>
ありがとうございました！変更できました！

2023-05-15 10:26 UTC, riennnn commented on pages/top.jsx
> +                    <button onClick={() => handleDeleteTodo(todo)} ml={5}><DeleteIcon /></button>
Iconに入れるとおかしくなったので、<Spacer />で書きました！

2023-05-15 10:26 UTC, riennnn commented on pages/top.jsx
> +            </Thead>
ありがとうございます！変更済みです！

2023-05-18 00:59 UTC, shtk0119 submitted a review, later dismissed

2023-05-18 11:42 UTC, riennnn commented
スクリーンショット
<img width="1440" alt="スクリーンショット 2023-05-18 20 40 10" src="https://github.com/if-mentor/next_todo10/assets/107998390/96507d63-2d0e-4b45-8805-60b40d4bd604">
デザイン最終修正しました

2023-05-19 15:22 UTC, sei693 commented on pages/top.jsx
> +          </Box>
Editアイコンですが、親のBoxにdisplay=flexを付けているので横並び＆右に寄せたいからmlを指定しているかと思いますが、<ResetButton />と＜Box>の間に<Spacer />を使うと、mlで指定しなくても右端に配置されるかと思います。
Spacerはchakraui独自のものになるので、TableContainer等と同様にimportする必要があります

2023-05-20 05:29 UTC, riennnn commented on pages/top.jsx
> +          </Box>
修正しました！ありがとうございます。

2023-05-20 12:33 UTC, sei693 approved these changes
問題ないと思います。

2023-05-20 13:21 UTC, merged